services:
  - type: web
    name: symfony-ai-demo
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false # Tutaj wkleisz link do bazy Neon.tech w panelu Render
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
